name: flutter_weather
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.3
  flutter_bloc:
    path: ../../packages/flutter_bloc
  google_fonts: ^1.1.0
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
    path: ../../packages/bloc_test
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
